# Generated by Django 4.0.1 on 2022-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=10)),
                ('class_expire', models.CharField(max_length=150)),
                ('class_teacher_name', models.CharField(max_length=150)),
                ('class_teacher_image', models.ImageField(upload_to='classes')),
                ('class_number_image', models.ImageField(upload_to='classes')),
            ],
        ),
    ]
