# Generated by Django 4.0.1 on 2022-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_classnumbers_teachers_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='weekdays',
            field=models.CharField(choices=[('Dushanba', 'Dushanba'), ('Seshanba', 'Seshanba'), ('Chorshanba', 'Chorshanba'), ('Payshanba', 'Payshanba'), ('Juma', 'Juma'), ('Shanba', 'Shanba')], max_length=250),
        ),
    ]
